services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: groupchat-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/group-chat
      - PORT=3000
      - JWT_SECRET=your_jwt_secret
    expose:
      - '3000'
    depends_on:
      - mongo
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: groupchat-frontend
    expose:
      - '80'
    depends_on:
      - backend
  nginx:
    image: nginx:1.26
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
volumes:
  mongodata: 